title: MW Test Consultancy
email: mark@mwtestconsultancy.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Training and insights into test automation and automation in testing practises
baseurl: ""
author: Mark Winteringham
url: "http://www.mwtestconsultancy.co.uk/"
twitter:
  username: 2bittester
github_username:  mwinteringham

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

highlighter: rouge

plugins:
  - jekyll-feed

collections:
  training:
    output: true
    permalink: /training/:path/

sass:
  style: compact

plugins:
- jekyll-seo-tag
